# Generated by Django 2.2.7 on 2019-11-21 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
