# Generated by Django 2.2.7 on 2019-11-21 03:34

import Apis.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apis', '0002_auto_20191121_0955'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('sex', models.IntegerField(choices=[(1, '男'), (2, '女')], error_messages={'blank': 'no blank', 'null': 'no null'})),
            ],
        ),
        migrations.AlterField(
            model_name='goods',
            name='name',
            field=models.CharField(max_length=200, validators=[Apis.models.name_min]),
        ),
    ]
