# Generated by Django 2.2.7 on 2019-11-21 03:45

import Apis.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apis', '0003_auto_20191121_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='默认', max_length=20, validators=[Apis.models.name_min]),
        ),
    ]
