# Generated by Django 2.2.7 on 2019-11-21 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apis', '0004_auto_20191121_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default=123456, max_length=20),
        ),
    ]
